SELECT TOP (1000) [id]
      ,[name]
      ,[description]
      ,[icon]
      ,[color]
      ,[parent_zone_id]
      ,[sort_order]
      ,[created_at]
      ,[updated_at]
  FROM [signals].[dbo].[zones]
